### ISSUE TITLE
Unable to run URControl

### ISSUE THREAD

**Issue by aswinthomas** [arunavanag591/ursim#1]
Thank you for the write up. Unfortunately Im having the following issue. Have you encountered this
```
./URControl 
./URControl: error while loading shared libraries: libxmlrpc_client++.so.8: cannot open shared object file: No such file or directory
```
I have installed libxmlrpc-c++8-dev

If i create a sym link ```sudo ln -s /usr/lib/x86_64-linux-gnu/libxmlrpc_client++.so /usr/lib/libxmlrpc_client++.so.8```

It gives
```
./URControl 
./URControl: error while loading shared libraries: libxmlrpc_client++.so.8: wrong ELF class: ELFCLASS64
```

**Comment by aswinthomas** [comment]
Looks like the URConctrol is i386 exe
After enabling i386 as per [this](https://wiki.debian.org/Multiarch/HOWTO) link I was able to ```sudo apt install libxmlrpc-c++8-dev:i386```

Now it gives 
```
./URControl 
mlockall failed:: Cannot allocate memory
00:00:00:000 INFO    - parseOpts(): The following ports will be used: Primary - 30001, Secondary - 30002, Matlab - 30003, RTDE - 30004, Primary_read_only - 30011, Secondary_read_only - 30012, Matlab_read_only - 30013.
URControl 7.0.21 [] G3 (20-09-2018, 07:45:28)
ConfigurationManager::ConfigurationManager() calling exit(EXIT_FAILURE)
URControl::shutdown
00:00:00:000 WARNING - loadCalibration: Error: Cannot open configuration file '/home/aswin/.urcontrol/calibration.conf'. The file is corrupt or missing.
00:00:00:000 INFO    - ConfigurationManager::loadConfiguration: Loading urcontrol.conf from: /home/aswin/.urcontrol/urcontrol.conf.

00:00:00:000 ERROR   - ConfigurationManager::loadConfiguration: Exception caught - Error: Cannot open configuration file '/home/aswin/.urcontrol/urcontrol.conf'. The file is corrupt or missing..

00:00:00:000 ERROR   - ConfigurationManager::ConfigurationManager: Configuration file could not be loaded!

00:00:00:000 ERROR   - Mutex, Unknown- Could not destroy the mutex. Error code = 16
```

**Comment by alexanderwatanabe** [comment]
I have the same problem in ursim-5.1.2.40245 as well as earlier versions

**Comment by aswinthomas** [comment]
I eventually got rid of the issue, but cant remember what exactly i did. Always run ./start-sim. If there are any errors on not finding files, take a look at the hidden folders and rename them to what the program is looking for (only if needed!)
I also have to run ur sim two times, since the first time UR control doesnt start.

**Comment by aeciolevy** [comment]
> apt install libxmlrpc-c++8-dev:i386

Was this running in macOS? 

I cannot get rig of this issue while running URControl

```
utility::LockQueue::LockQueue() Mutex::Mutex() calling exit(-1)
```
